name: todo_getx_isar_fa_ff
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Localizations
  flutter_localizations:
    sdk: flutter    
  # Gerenciador de estados
  get: ^4.6.1
  # LocalStorage
  isar: 2.2.1
  isar_flutter_libs: 2.2.1
  # Firebase (Authentication)
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1  
  cloud_firestore: ^3.1.10
  # Google
  google_sign_in: ^5.2.4
  google_fonts: ^2.3.1
  # outros
  uuid: ^3.0.6
  validatorless: ^1.2.1
  intl: ^0.17.0
  synchronized: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  isar_generator: 2.2.1
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
